apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
      - name: estoque
        image: fangzereda/estoque:1.0.0
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"        
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 15
